### ISSUE TITLE
Does not use correct brackets when cursor is after them.

### ISSUE THREAD

**Issue by DasOhmoff** [Spenny1068/ciBracket#3]
Hey. Thank you for this plugin!

When one tries to delete within nested brackets, and the cursor is after them. Then the wrong brackets get selected for deletion.

Example (`^` signifies the cursor position):
* *before:* `( 1 ( 2 ) 3 ) ^`
* *after:* `( 1 (^) 3 )`

Expected behaviour (`^` signifies the cursor position):
* *before:* `( 1 ( 2 ) 3 ) ^`
* *after:* `(^)`

**Comment by Spenny1068** [comment]
Thanks for the issue! It should be fixed now :)

**Comment by DasOhmoff** [comment]
Thanks!
